services:
  api:
    restart: unless-stopped
    build: ./api
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  website:
    restart: unless-stopped
    build: ./website
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_REST_API_BASE_URL: ${NEXT_PUBLIC_REST_API_BASE_URL}

volumes:
  pgdata:
